id = "smbcloud-zed-extension"
name = "smbCloud Zed Extension"
description = "Easy deployment with smbCloud Zed Extension."
version = "0.1.0"
schema_version = 1
authors = ["smbCloud <smbcloud@setoelkahfi.se>"]
repository = "https://github.com/smbcloudXYZ/smbcloud-zed-extension"

[slash_commands.echo]
description = "echoes the provided input"
requires_argument = true

[slash_commands.pick-one]
description = "pick one of three options"
requires_argument = true
